services:
  app:
    build:
      context: .
    ports:
      - "3500:3500"
    volumes:
      - .:/usr/src/app
      - ./linux/logrotate.d/app:/etc/logrotate.d/app
    working_dir: /usr/src/app
    tty: true
    command: sh -c "go mod tidy && go build cmd/masmaint/main.go && ./main"
    restart: always
